### ISSUE TITLE
Unsupported platform when deploying via docker swarm

### ISSUE THREAD

**Issue by charlieparkes** [itsTeckel/vu#4]
I'm receiving an error from docker swarm when this container starts.

> no suitable node (unsupported platform)

The nodes are running intel x64 processors w/ an x64 kernel on debain 10. Before taking a deep dive into the container, I was wondering if you've run into this as well.

Here's my compose file, for reference, if you want to try it yourself. (Since, presumably, most of us run a similar cpu/kernel.) I believe the issue is specific to docker swarm, after digging a bit.

```bash
docker stack deploy --with-registry-auth -c /var/bf3/docker-compose.yml battlefield3

# tear-down with 'docker stack rm battlefield3'
```

```yaml
version: "3.8"

services:
    server:
        image: itsteckel/vu:latest
        ports:
            - 47200:47200/tcp
            - 7948:7948/udp
            - 25200:25200/udp
        environment:
            O_EMAIL: "foo@bar.com"
            O_PASSWORD: "foobar"
        volumes:
            - '/var/bf3/data/bf3:/vu/bf3'
            - '/var/bf3/data/instance:/vu/instance'
            - 'client:/vu/client'
        deploy:
            restart_policy:
                condition: on-failure

volumes:
    client:
```
